name: ci

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ vars.WWW_APP_URL }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/workflows/setup

      - name: Build artifacts
        env:
          WWW_APP_URL: ${{ vars.WWW_APP_URL }}
        run: pnpm run build

      - name: Deploy artifacts
        run: |
          git remote set-url origin https://git:${{secrets.IAMSHGULATI_GITHUB_IO_TOKEN}}@github.com/${{vars.WWW_APP_REPO}}.git
          pnpm run deploy --cname www.shubhamgulati.com --no-history --user "github-actions-bot <support+actions@github.com>" --message "feat(www): deploy"

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/workflows/setup

      - name: Typecheck
        run: pnpm run typecheck

  lint:
    # if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/workflows/setup

      - name: Copy env
        shell: bash
        run: cp .env.example .env

      - name: Lint
        run: pnpm run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/workflows/setup

      - name: Format
        run: pnpm run format
